db:
  credentials:   'postgres:badpassword'
  host:     postgres
  database: event_calendar

uploads:
  max_upload_size: 10485760 # 10MB
  extensions:
    - png
    - jpg
    - jpeg
  public: /var/calendar/data/uploads
  draft:  /var/calendar/data/draft-uploads

password_reset:
  expires: 600 #seconds

email:
  server: smtp.gmail.com #for development only
