LanguageCode:
  type: string
  enum:
    - aa # Afar
    - ab # Abkhazian
    - ae # Avestan
    - af # Afrikaans
    - ak # Akan
    - am # Amharic
    - an # Aragonese
    - ar # Arabic
    - as # Assamese
    - av # Avaric
    - ay # Aymara
    - az # Azerbaijani
    - ba # Bashkir
    - be # Belarusian
    - bg # Bulgarian
    - bh # Bihari languages
    - bi # Bislama
    - bm # Bambara
    - bn # Bengali
    - bo # Tibetan
    - br # Breton
    - bs # Bosnian
    - ca # Catalan; Valencian
    - ce # Chechen
    - ch # Chamorro
    - co # Corsican
    - cr # Cree
    - cs # Czech
    - cu # Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic
    - cv # Chuvash
    - cy # Welsh
    - da # Danish
    - de # German
    - dv # Divehi; Dhivehi; Maldivian
    - dz # Dzongkha
    - ee # Ewe
    - el # Greek, Modern (1453-)
    - en # English
    - eo # Esperanto
    - es # Spanish; Castilian
    - et # Estonian
    - eu # Basque
    - fa # Persian
    - ff # Fulah
    - fi # Finnish
    - fj # Fijian
    - fo # Faroese
    - fr # French
    - fy # Western Frisian
    - ga # Irish
    - gd # Gaelic; Scottish Gaelic
    - gl # Galician
    - gn # Guarani
    - gu # Gujarati
    - gv # Manx
    - ha # Hausa
    - he # Hebrew
    - hi # Hindi
    - ho # Hiri Motu
    - hr # Croatian
    - ht # Haitian; Haitian Creole
    - hu # Hungarian
    - hy # Armenian
    - hz # Herero
    - ia # Interlingua (International Auxiliary Language Association)
    - id # Indonesian
    - ie # Interlingue; Occidental
    - ig # Igbo
    - ii # Sichuan Yi; Nuosu
    - ik # Inupiaq
