openapi: 3.0.0
info: 
  title: Community Events API
  description: event management api
  version: 1.0.0
  contact:
    name: Author
    email: stephen@enterity.com
servers:
  - url: https://dev.community-events.com/v1
    description: Development server
components:
  parameters:
    startParam:
      name: start
      in: query
      schema:
        type: string
        format: date
    endParam:
      name: end
      in: query
      schema:
        type: string
        format: date
    categoryParam:
      name: category
      in: query
      schema:
        type: array
        items:
          oneOf:
            - type: string # category id
              format: uuid
            - type: string # category name
  responses:
    NotFound:
      description: Not Found
    Ok:
      description: Ok
  schemas:
    Category:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        parent:
            oneOf:
              - type: string
                format: uuid
              - $ref: '#/components/schemas/Category'
        children:
            type: array
            items:
              oneOf:
                - type: string
                  format: uuid
                - $ref: '#/components/schemas/Category'
    Image:
      properties:
        title:
          type: string
        description:
          type: string
        data:
          type: string
          format: byte
    Event:
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
        categories:
          type: array
          items:
            oneOf:
              - type: string
                format: uuid
              - $ref: '#/components/schemas/Category'
        events:
          type: array
          items:
            oneOf:
              - type: string
                format: uuid
              - $ref: '#/components/schemas/Event'

paths:
  /events:
    get:
      parameters:
        - $ref: '#/components/parameters/categoryParam'
        - $ref: '#/components/parameters/startParam'
        - $ref: '#/components/parameters/endParam'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          $ref: '#/components/responses/Ok'

  /events/{event}:
    parameters:
      - in: path
        name: event
        required: true
        schema:
          type: string
          format: uuid
    get:
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      operationId: app.events.update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          $ref: '#/components/responses/Ok'
  /categories:
    get:
      parameters:
        - in: query
          name: category
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/Ok'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          $ref: '#/components/responses/Ok'
  /categories/{category}:
    parameters:
      - in: path
        name: category
        required: true
        schema:
          type: string
          format: uuid
    get:
      responses:
        '200':
          $ref: '#/components/responses/Ok'
    post:
      operationId: app.categories.update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          $ref: '#/components/responses/Ok'
